server:
  port: 8000

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: POSTGRESQL
    data: classpath:data.sql
    schema: classpath:schema_post.sql
    url: jdbc:postgresql://10.222.41.241:5432/MartinDemo?ssl=true&user=postgres&password=IGTtest1
  
    